Uses a different method for calling wp-load.php.
Plugin was failing on a particular server with this error:

Warning: require_once(E:\webserver\www-dev\dev-blog-gov-bc-ca/wp-load.php): failed to open stream: No such file or directory in E:\webserver\www-dev\dev-blog-gov-bc-ca\content\plugins\wp-placespeak-connect-master\oauth_redirect.php on line 26

Fatal error: require_once(): Failed opening required 'E:\webserver\www-dev\dev-blog-gov-bc-ca/wp-load.php' (include_path='.;C:\php\pear') in E:\webserver\www-dev\dev-blog-gov-bc-ca\content\plugins\wp-placespeak-connect-master\oauth_redirect.php on line 26

I think this may be because the load path for wp-load.php is making assumptions, rather than the pear library not being installed to PHP. Attempting to load wp-load.php in a different way, as a test of that that theory.

This loading approach comes from https://frankiejarrett.com/2012/04/the-simplest-way-to-require-include-wp-load-php/